version: "3"
services:
  backend:
    container_name: backend
    restart: always
    build: .
    command: >
      bash -c
      "
      sleep 20s &
      cd ./Backend
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8001"
    volumes:
      - .:/code
    expose:
      - "8080"
    networks:
      - web_network
  nginx:
    container_name: Nginx
    restart: always
    image: nginx:latest
    ports:
      - "8001:8001"
      - "8000:8000"
    volumes:
      - ./Backend/config/nginx:/etc/nginx/conf.d
      - ./Frontend/ml-platform/deploy/nginx:/etc/nginx/conf.d
    depends_on:
      - backend
    networks:
      - web_network

networks:
  web_network:
    driver: bridge

volumes:
  static-volume: