version: "3"
services:
  backend:
    container_name: backend
    restart: always
    build: Backend
    # command: >
    #   bash -c
    #   "
    #   dir /code
    #   sleep 20s &&
    #   cd  &&
    #   python manage.py makemigrations &&
    #   python manage.py migrate &&
    #   uwsgi --ini docker_test.ini"
    volumes:
      - .:/code
    expose:
      - "8001"
    ports:
      - "8001:8001"
    networks:
      - web_network
    command: uwsgi --ini /code/Backend/config/docker_test.ini
  nginx:
    container_name: nginx
    restart: always
    image: nginx:latest
    ports:
      - "8000:8000"
      # - "8001:8001"
    # volumes:
    #   - ./Backend/config/nginx:/etc/nginx/conf.d
    depends_on:
      - backend
    build: Frontend/ml-platform 
    expose:
      - "8000"
    networks:
      - web_network

networks:
  web_network:
    driver: bridge

volumes:
  static-volume: